services:
  attendance-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: attendance-service
    volumes:
      - .:/app
    ports:
      - "8003:8000"
    depends_on:
      - db
    environment:
      - DB_URL=postgresql+asyncpg://postgres:postgres@attendance-db:5432/attendance_db
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    networks:
      - attendance_net

  db:
    image: postgres:15
    container_name: attendance-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - attendance_net

volumes:
  postgres_data:

networks:
  attendance_net:
    external: true